name: Build LaTeX document
on:
  push:
    paths:
      - '**.tex'
      - '**.cls'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Clone resume repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume-zh.tex
          latexmk_use_xelatex: true
          extra_fonts: |
            ./fonts/*.otf
      - name: Upload PDF file to release
        uses: actions/upload-artifact@v4
        with:
          name: resume-zh.pdf
          path: resume-zh.pdf
      - name: Upload PDF file to docs
        run: |
          cp -RT resume-zh.pdf docs/resume-zh.pdf
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -f docs/resume-zh.pdf
          git commit -m "resume-zh.pdf update"
          git push
          
